name: commit-message-test

on:
  push:

jobs:
  print-commit-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print commit message
        shell: bash
        run: echo "${{github.event.commit_head.message}}"