name: commit-message-test

on:
  push:

jobs:
  print-commit-message:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'aribalam' && (contains(github.ref, 'doc') || contains(github.event.head_commit.message, '[build_docs]'))

    steps:
      - uses: actions/checkout@v2

      - name: Print commit message
        shell: bash
        run: echo "${{ github.event.head_commit.message }}"

      - name: Print branch name
        shell: bash
        run: echo "${{ toJSON(github.ref) }}"